language: node_js
node_js:
- '7.10'
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
- ng build --prod
deploy:
  provider: surge
  domain: ng4-mvp-toolkit.surge.sh
  skip_cleanup: true
  project: ./dist/
